project_id = "vqvhwicknmaccgxvunww"

[functions.send-project-notification]
verify_jwt = false

[functions.check-deadlines]
verify_jwt = false

[functions.check-reminders]
verify_jwt = false

[functions.sync-google-calendar]
verify_jwt = false

[functions.send-welcome-email]
verify_jwt = false